### PR TITLE
Add extension point to configure the SpringApplicationBuilder for #4

### PR DESCRIPTION
**Pull request by bassman5**
Update spring-boot-starter-parent to 1.2.1-RELEASE
Update release to 1.0.2-RELEASE
Add .gitignore for Intellij

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks for the patch. In case this code ever goes into an official Spring project, can you confirm that you filled out the Spring CLA (https://support.springsource.com/spring_committer_signup)?

**Comment by bassman5** [comment]
Yes I have completed the Spring CLA, my confirmation number is 149520151119025004

**Comment by bassman5** [comment]
BTW I found that Spring Boot 1.3 would not start on GAE because 1.3 uses a BackgroundPreinitializer with a ThreadPoolExecutor which is backlisted in GAE.
I have a 'hack' to remove the BackgroundPreinitializer and add a ForegroundPreinitializer based on this PR if you are interested. 
With this I have a simple Spring Boot 1.3 app running on GAE.

**Comment by dsyer** [comment]
Sounds good. Please send another PR by all means.

**Comment by dsyer** [comment]
Too many conflicts. Probably obsolete anyway. Please send another PR if I missed something.

**Pull request closed without merging**
